version: "3"
services:
  mailtrap:
    image: dbck/mailtrap:latest
    init: true
    environment:
      # - TZ=Europe/Berlin
      - MAILTRAP_USER=username
      - MAILTRAP_PASSWORD=password
    volumes:
      - maildata:/var/mail
    ports:
      - "9025:25"
      - "9465:465"
      - "9587:587"
      - "9143:143"
      - "9993:993"
      - "9080:80"
volumes:
  maildata: